"""
Prompt builder.

Turns a `MergedEvidence` object into the single text prompt sent to
Gemini together with the screenshot. Kept separate from gemini_client.py
so the prompt can be iterated on (or unit-tested) without touching the
API-calling code, and so a future second LLM provider can reuse the
exact same prompt.
"""
from app.services.evidence.evidence_merger import MergedEvidence

RESPONSE_JSON_SHAPE = """{
  "title": string,
  "summary": string,
  "description": string,
  "severity": "Critical" | "High" | "Medium" | "Low",
  "priority": "P0" | "P1" | "P2" | "P3",
  "environment": string | null,
  "module": string | null,
  "bug_type": string | null,
  "expected_result": string | null,
  "actual_result": string | null,
  "possible_root_cause": string | null,
  "confidence_score": number (0-100),
  "steps_to_reproduce": string[],
  "suggested_labels": string[],
  "follow_up_questions": string[]
}"""


def build_prompt(evidence: MergedEvidence) -> str:
    """Builds the full instruction + evidence prompt for Gemini."""

    evidence_lines = []

    if evidence.user_description:
        evidence_lines.append(f"User Description:\n{evidence.user_description}")

    if evidence.browser_url:
        evidence_lines.append(f"Browser URL:\n{evidence.browser_url}")

    if evidence.console_log:
        evidence_lines.append(f"Console Log:\n{evidence.console_log}")

    if evidence.stack_trace:
        evidence_lines.append(f"Stack Trace:\n{evidence.stack_trace}")

    evidence_block = "\n\n".join(evidence_lines) if evidence_lines else "(No additional text evidence provided.)"

    return f"""You are a senior QA engineer and bug triage expert. You are given a
screenshot of a software application plus optional supporting evidence
below. Analyze ALL of the evidence together as one connected story —
do not treat the screenshot and the text evidence as unrelated inputs.

Analyze the screenshot for:
- UI components, buttons, forms, tables, dialogs, toast/snackbar messages
- Any visible error messages
- Any visible browser chrome or URL
- Overall look of the screen (module/page it likely belongs to)
- Any readable text in the image (OCR)

Cross-reference that with the text evidence below (console errors, stack
trace, user description, browser URL) to figure out the relationship
between what the user saw and what technically went wrong.

--- TEXT EVIDENCE ---
{evidence_block}
--- END TEXT EVIDENCE ---

Produce a bug report as a SINGLE JSON object with EXACTLY this shape
(no markdown fences, no commentary before or after the JSON):

{RESPONSE_JSON_SHAPE}

Rules:
- "confidence_score" reflects how confident you are in the overall
  report given the evidence actually provided (low if the screenshot is
  ambiguous or evidence is sparse/contradictory).
- "follow_up_questions" must be DYNAMICALLY generated by you based on
  what is actually missing or unclear for THIS report — never a generic
  fixed list. Return an empty array if you are confident and nothing is
  missing.
- "steps_to_reproduce" should be your best reconstruction from the
  evidence, ordered, concise, actionable.
- Use null (not empty string) for any field you genuinely cannot infer.
- Return ONLY the JSON object.
"""
